"""Create clientes table and related tables

Revision ID: 07af028af52e
Revises: 5ee30ffa9e84
Create Date: 2025-08-11 20:44:35.456742

"""
from typing import Sequence, Union

from alembic import op
from alembic import context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07af028af52e'
down_revision: Union[str, Sequence[str], None] = '324418f810fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(conn, table: str, column: str) -> bool:
    r = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = :t AND column_name = :c"
    ), {"t": table, "c": column})
    return r.scalar() is not None


def upgrade() -> None:
    """Upgrade schema."""
    conn = context.get_bind()
    if not _column_exists(conn, 'orcamentos', 'condicao_pagamento'):
        op.add_column('orcamentos', sa.Column('condicao_pagamento', sa.String(), nullable=True))
    if not _column_exists(conn, 'orcamentos', 'preco_minimo'):
        op.add_column('orcamentos', sa.Column('preco_minimo', sa.Float(), nullable=True))
    if not _column_exists(conn, 'orcamentos', 'preco_maximo'):
        op.add_column('orcamentos', sa.Column('preco_maximo', sa.Float(), nullable=True))
    if not _column_exists(conn, 'orcamentos', 'numero_nf'):
        op.add_column('orcamentos', sa.Column('numero_nf', sa.String(), nullable=True))
    if not _column_exists(conn, 'orcamentos', 'cliente_id'):
        op.add_column('orcamentos', sa.Column('cliente_id', sa.Integer(), nullable=True))
    # FK: verificar se já existe (nome pode ser gerado)
    r = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.table_constraints c "
        "JOIN information_schema.key_column_usage k ON c.constraint_name = k.constraint_name "
        "WHERE c.table_schema = 'public' AND c.table_name = 'orcamentos' AND c.constraint_type = 'FOREIGN KEY' AND k.column_name = 'cliente_id'"
    ))
    if r.scalar() is None:
        op.create_foreign_key('fk_orcamentos_cliente_id', 'orcamentos', 'clientes', ['cliente_id'], ['id'])
    if _column_exists(conn, 'orcamentos', 'nome_cliente'):
        op.drop_column('orcamentos', 'nome_cliente')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamentos', sa.Column('nome_cliente', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orcamentos', type_='foreignkey')
    op.drop_column('orcamentos', 'cliente_id')
    op.drop_column('orcamentos', 'numero_nf')
    op.drop_column('orcamentos', 'preco_maximo')
    op.drop_column('orcamentos', 'preco_minimo')
    op.drop_column('orcamentos', 'condicao_pagamento')
    # ### end Alembic commands ###
