"""Create clientes table and related tables

Revision ID: 07af028af52e
Revises: 5ee30ffa9e84
Create Date: 2025-08-11 20:44:35.456742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07af028af52e'
down_revision: Union[str, Sequence[str], None] = '324418f810fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamentos', sa.Column('condicao_pagamento', sa.String(), nullable=True))
    op.add_column('orcamentos', sa.Column('preco_minimo', sa.Float(), nullable=True))
    op.add_column('orcamentos', sa.Column('preco_maximo', sa.Float(), nullable=True))
    op.add_column('orcamentos', sa.Column('numero_nf', sa.String(), nullable=True))
    op.add_column('orcamentos', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orcamentos', 'clientes', ['cliente_id'], ['id'])
    op.drop_column('orcamentos', 'nome_cliente')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamentos', sa.Column('nome_cliente', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orcamentos', type_='foreignkey')
    op.drop_column('orcamentos', 'cliente_id')
    op.drop_column('orcamentos', 'numero_nf')
    op.drop_column('orcamentos', 'preco_maximo')
    op.drop_column('orcamentos', 'preco_minimo')
    op.drop_column('orcamentos', 'condicao_pagamento')
    # ### end Alembic commands ###
