"""Adiciona colunas xp e level para Usuario

Revision ID: 0fe93d7f6dd1
Revises: 
Create Date: 2025-08-05 19:50:34.468974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe93d7f6dd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('xp', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'level')
    op.drop_column('usuarios', 'xp')
    # ### end Alembic commands ###
