"""add_historico_pagamento_table

Revision ID: 4ba406ef5479
Revises: 07af028af52e
Create Date: 2025-08-12 03:14:32.001653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4ba406ef5479'
down_revision: Union[str, Sequence[str], None] = '07af028af52e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add missing columns to historico_pagamentos table
    op.add_column('historico_pagamentos', sa.Column('data_vencimento', sa.Date(), nullable=False, server_default='2024-01-01'))
    op.add_column('historico_pagamentos', sa.Column('numero_nf', sa.String(), nullable=True))
    op.add_column('historico_pagamentos', sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('historico_pagamentos', sa.Column('orcamento_id', sa.Integer(), nullable=True))
    
    # Add foreign key constraint for orcamento_id
    op.create_foreign_key('fk_historico_pagamentos_orcamento_id', 'historico_pagamentos', 'orcamentos', ['orcamento_id'], ['id'])
    
    # Remove server_default after adding the column
    op.alter_column('historico_pagamentos', 'data_vencimento', server_default=None)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove foreign key constraint
    op.drop_constraint('fk_historico_pagamentos_orcamento_id', 'historico_pagamentos', type_='foreignkey')
    
    # Remove added columns
    op.drop_column('historico_pagamentos', 'orcamento_id')
    op.drop_column('historico_pagamentos', 'data_criacao')
    op.drop_column('historico_pagamentos', 'numero_nf')
    op.drop_column('historico_pagamentos', 'data_vencimento')
    
    # ### end Alembic commands ###
