"""add_historico_pagamento_table

Revision ID: 4ba406ef5479
Revises: 07af028af52e
Create Date: 2025-08-12 03:14:32.001653

"""
from typing import Sequence, Union

from alembic import op
from alembic import context
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4ba406ef5479'
down_revision: Union[str, Sequence[str], None] = '07af028af52e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(conn, table: str, column: str) -> bool:
    r = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = :t AND column_name = :c"
    ), {"t": table, "c": column})
    return r.scalar() is not None


def _fk_exists(conn, table: str, column: str) -> bool:
    r = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.table_constraints c "
        "JOIN information_schema.key_column_usage k ON c.constraint_name = k.constraint_name "
        "WHERE c.table_schema = 'public' AND c.table_name = :t AND c.constraint_type = 'FOREIGN KEY' AND k.column_name = :col"
    ), {"t": table, "col": column})
    return r.scalar() is not None


def upgrade() -> None:
    """Upgrade schema."""
    conn = context.get_bind()
    if not _column_exists(conn, 'historico_pagamentos', 'data_vencimento'):
        op.add_column('historico_pagamentos', sa.Column('data_vencimento', sa.Date(), nullable=False, server_default='2024-01-01'))
        op.alter_column('historico_pagamentos', 'data_vencimento', server_default=None)
    if not _column_exists(conn, 'historico_pagamentos', 'numero_nf'):
        op.add_column('historico_pagamentos', sa.Column('numero_nf', sa.String(), nullable=True))
    if not _column_exists(conn, 'historico_pagamentos', 'data_criacao'):
        op.add_column('historico_pagamentos', sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    if not _column_exists(conn, 'historico_pagamentos', 'orcamento_id'):
        op.add_column('historico_pagamentos', sa.Column('orcamento_id', sa.Integer(), nullable=True))
    if not _fk_exists(conn, 'historico_pagamentos', 'orcamento_id'):
        op.create_foreign_key('fk_historico_pagamentos_orcamento_id', 'historico_pagamentos', 'orcamentos', ['orcamento_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove foreign key constraint
    op.drop_constraint('fk_historico_pagamentos_orcamento_id', 'historico_pagamentos', type_='foreignkey')
    
    # Remove added columns
    op.drop_column('historico_pagamentos', 'orcamento_id')
    op.drop_column('historico_pagamentos', 'data_criacao')
    op.drop_column('historico_pagamentos', 'numero_nf')
    op.drop_column('historico_pagamentos', 'data_vencimento')
    
    # ### end Alembic commands ###
