"""Adiciona tabelas de compras e fornecedores e relaciona com produtos

Revision ID: 6283e7d01c3b
Revises: 0fe93d7f6dd1
Create Date: 2025-08-06 15:27:46.278641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6283e7d01c3b'
down_revision: Union[str, Sequence[str], None] = '0fe93d7f6dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # op.create_table('fornecedores',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('nome', sa.String(), nullable=False),
    #sa.Column('cnpj', sa.String(), nullable=True),
    #sa.Column('contato_email', sa.String(), nullable=True),
    #sa.Column('contato_telefone', sa.String(), nullable=True),
    #sa.Column('empresa_id', sa.Integer(), nullable=True),
    #sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    #sa.PrimaryKeyConstraint('id'),
    #sa.UniqueConstraint('cnpj')
    #op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    #op.create_index(op.f('ix_fornecedores_nome'), 'fornecedores', ['nome'], unique=True)
   # op.create_table('ordens_compra',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    #sa.Column('usuario_id', sa.Integer(), nullable=True),
    #sa.Column('status', sa.String(), nullable=True),
   # sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    #sa.Column('data_recebimento', sa.DateTime(timezone=True), nullable=True),
    #sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    #sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    #sa.PrimaryKeyConstraint('id')
    #)
   # op.create_index(op.f('ix_ordens_compra_id'), 'ordens_compra', ['id'], unique=False)
   # op.create_table('ordens_compra_itens',
   # sa.Column('id', sa.Integer(), nullable=False),
  #  sa.Column('ordem_id', sa.Integer(), nullable=True),
#    sa.Column('produto_id', sa.Integer(), nullable=True),
 #   sa.Column('quantidade_solicitada', sa.Integer(), nullable=False),
  #  sa.Column('custo_unitario_registrado', sa.Float(), nullable=False),
   # sa.ForeignKeyConstraint(['ordem_id'], ['ordens_compra.id'], ),
    #sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    #sa.PrimaryKeyConstraint('id')
   # )
    #op.create_index(op.f('ix_ordens_compra_itens_id'), 'ordens_compra_itens', ['id'], unique=False)
    #op.add_column('produtos', sa.Column('fornecedor_id', sa.Integer(), nullable=True))
    #op.create_foreign_key(None, 'produtos', 'fornecedores', ['fornecedor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # op.drop_constraint(None, 'produtos', type_='foreignkey')
   # op.drop_column('produtos', 'fornecedor_id')
  #  op.drop_index(op.f('ix_ordens_compra_itens_id'), table_name='ordens_compra_itens')
   # op.drop_table('ordens_compra_itens')
  ##  op.drop_index(op.f('ix_ordens_compra_id'), table_name='ordens_compra')
    #op.drop_table('ordens_compra')
  #  op.drop_index(op.f('ix_fornecedores_nome'), table_name='fornecedores')
   # op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    #op.drop_table('fornecedores')
    # ### end Alembic commands ###
